package app

import (
	"errors"
	"strings"
	"testing"
	"time"
)

// fakeRelStore is a minimal in-memory RelationStore implementation that
// records the last call for assertion. Combined with the embedded
// fakeStore it satisfies both Store and RelationStore so the service
// can dispatch through the capability type-assert.
type fakeRelStore struct {
	fakeStore

	createCalls   int
	lastSrc       int64
	lastTgt       int64
	lastType      string
	lastAt        time.Time
	createErr     error

	neighborsCalls int
	lastID         int64
	lastDir        RelationDirection
	neighborsRet   []MemoryRelation
	neighborsErr   error
}

func (f *fakeRelStore) CreateRelation(src, tgt int64, t string, at time.Time) error {
	f.createCalls++
	f.lastSrc = src
	f.lastTgt = tgt
	f.lastType = t
	f.lastAt = at
	return f.createErr
}

func (f *fakeRelStore) Neighbors(id int64, dir RelationDirection) ([]MemoryRelation, error) {
	f.neighborsCalls++
	f.lastID = id
	f.lastDir = dir
	return f.neighborsRet, f.neighborsErr
}

// TestServiceRelate_ValidationRejectsBadInput covers task 3.3:
// service-layer guards must reject invalid inputs BEFORE touching the
// store so the friendly error message is the same regardless of which
// backing store is wired in.
func TestServiceRelate_ValidationRejectsBadInput(t *testing.T) {
	cases := []struct {
		name        string
		src, tgt    int64
		relType     string
		wantErrSub  string
	}{
		{"zero source", 0, 2, "related", "source id"},
		{"negative source", -1, 2, "related", "source id"},
		{"zero target", 1, 0, "related", "target id"},
		{"negative target", 1, -1, "related", "target id"},
		{"self loop rejected at service layer", 5, 5, "related", "self-loop"},
		{"empty type", 1, 2, "", "relation type"},
		{"whitespace type", 1, 2, "   ", "relation type"},
		{"unknown type", 1, 2, "invalid_type", "relation type"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			frs := &fakeRelStore{}
			svc := NewService(frs)
			err := svc.Relate(tc.src, tc.tgt, tc.relType)
			if err == nil {
				t.Fatalf("expected error, got nil")
			}
			if !strings.Contains(strings.ToLower(err.Error()), tc.wantErrSub) {
				t.Fatalf("error %q must mention %q", err.Error(), tc.wantErrSub)
			}
			if frs.createCalls != 0 {
				t.Fatalf("store.CreateRelation must NOT be called on validation failure (got %d)", frs.createCalls)
			}
		})
	}
}

// TestServiceRelate_HappyPathDelegatesToStore covers task 3.3:
// valid input must trim the relation type and dispatch to CreateRelation
// with a UTC timestamp generated by the service (callers don't pass time).
func TestServiceRelate_HappyPathDelegatesToStore(t *testing.T) {
	frs := &fakeRelStore{}
	svc := NewService(frs)
	if err := svc.Relate(1, 2, "  supersedes  "); err != nil {
		t.Fatalf("expected success, got %v", err)
	}
	if frs.createCalls != 1 {
		t.Fatalf("expected 1 CreateRelation call, got %d", frs.createCalls)
	}
	if frs.lastSrc != 1 || frs.lastTgt != 2 {
		t.Fatalf("ids mismatch: src=%d tgt=%d", frs.lastSrc, frs.lastTgt)
	}
	if frs.lastType != "supersedes" {
		t.Fatalf("relation type must be trimmed: got %q", frs.lastType)
	}
	if frs.lastAt.Location() != time.UTC {
		t.Fatalf("timestamp must be UTC, got %v", frs.lastAt.Location())
	}
	if frs.lastAt.IsZero() {
		t.Fatalf("timestamp must be stamped by service, got zero")
	}
}

// TestServiceRelate_PropagatesStoreError covers task 3.3:
// when the store rejects the insert (e.g. FK violation, duplicate self-
// loop discovered late), the service must surface the error verbatim so
// callers can distinguish validation rejections from DB-layer rejections.
func TestServiceRelate_PropagatesStoreError(t *testing.T) {
	wantErr := errors.New("FK target_id missing")
	frs := &fakeRelStore{createErr: wantErr}
	svc := NewService(frs)
	err := svc.Relate(1, 99, "related")
	if err == nil {
		t.Fatal("expected error from store, got nil")
	}
	if !errors.Is(err, wantErr) && !strings.Contains(err.Error(), wantErr.Error()) {
		t.Fatalf("store error must propagate, got %v", err)
	}
}

// TestServiceRelate_CapabilityMissing covers task 3.3:
// when the wired store does not implement RelationStore, the service
// MUST fail fast with an explicit capability error (same defensive
// pattern as MetadataStore / SessionStore).
func TestServiceRelate_CapabilityMissing(t *testing.T) {
	svc := NewService(&fakeStore{})
	err := svc.Relate(1, 2, "related")
	if err == nil {
		t.Fatal("expected capability error, got nil")
	}
	if !strings.Contains(strings.ToLower(err.Error()), "graph") &&
		!strings.Contains(strings.ToLower(err.Error()), "relation") {
		t.Fatalf("error must mention graph/relation capability, got %q", err.Error())
	}
}

// TestServiceNeighbors_ValidationRejectsBadIDs covers task 3.3:
// id must be positive; direction must be a known enum value.
func TestServiceNeighbors_ValidationRejectsBadIDs(t *testing.T) {
	cases := []struct {
		name string
		id   int64
		dir  RelationDirection
	}{
		{"zero id", 0, RelationDirectionOutbound},
		{"negative id", -1, RelationDirectionInbound},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			frs := &fakeRelStore{}
			svc := NewService(frs)
			_, err := svc.Neighbors(tc.id, tc.dir)
			if err == nil {
				t.Fatalf("expected validation error, got nil")
			}
			if frs.neighborsCalls != 0 {
				t.Fatalf("store.Neighbors must NOT be called on validation failure")
			}
		})
	}
}

// TestServiceNeighbors_HappyPathPassesDirection covers task 3.3:
// valid id + direction reaches the store unchanged.
func TestServiceNeighbors_HappyPathPassesDirection(t *testing.T) {
	want := []MemoryRelation{
		{ID: 10, SourceID: 1, TargetID: 2, RelationType: "related", CreatedAt: time.Unix(1700000000, 0).UTC()},
	}
	frs := &fakeRelStore{neighborsRet: want}
	svc := NewService(frs)
	got, err := svc.Neighbors(1, RelationDirectionOutbound)
	if err != nil {
		t.Fatalf("expected success, got %v", err)
	}
	if frs.neighborsCalls != 1 {
		t.Fatalf("expected 1 call, got %d", frs.neighborsCalls)
	}
	if frs.lastID != 1 || frs.lastDir != RelationDirectionOutbound {
		t.Fatalf("dispatch mismatch: id=%d dir=%v", frs.lastID, frs.lastDir)
	}
	if len(got) != 1 || got[0].ID != 10 {
		t.Fatalf("result not propagated: %+v", got)
	}
}

// TestServiceNeighbors_CapabilityMissing — same defensive guard as Relate.
func TestServiceNeighbors_CapabilityMissing(t *testing.T) {
	svc := NewService(&fakeStore{})
	_, err := svc.Neighbors(1, RelationDirectionOutbound)
	if err == nil {
		t.Fatal("expected capability error, got nil")
	}
}

// TestIsAllowedRelationType covers the whitelist guard exposed for
// reuse by MCP and any future surface.
func TestIsAllowedRelationType(t *testing.T) {
	for _, ok := range AllowedRelationTypes {
		if !IsAllowedRelationType(ok) {
			t.Errorf("whitelist self-check failed for %q", ok)
		}
	}
	for _, bad := range []string{"", "RELATED", "unknown", "supersede"} {
		if IsAllowedRelationType(bad) {
			t.Errorf("invalid type %q should not be allowed", bad)
		}
	}
}
